config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :weather do 
    get :index
  end

  namespace :cities do
    get :autocomplete
  end
  root to: 'weather#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

  AUTOCOMPLETE_LIMIT = 10
  
  def self.autocomplete(query)
    where("name ILIKE ?","#{query}%").limit(AUTOCOMPLETE_LIMIT).select("(name || ', ' || country_code) as name, open_map_id as id")
  end

  def self.get_weather(city_id, city_name)
    if city_id.to_i == 0
      return Services::OpenWeatherMapSao.get_weather_by_city_name(city_name)
    else
      # assuming weather report is updated every 6 - 12 hours
      open_weather_response = Rails.cache.fetch("open_weather_response:#{city_id}", :expires_in => 6.hours) do
        Services::OpenWeatherMapSao.get_weather_by_city_id(city_id)
      end
      return open_weather_response
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def autocomplete
    render :json => [], :status => 400 and return unless params[:q].present?
    render :json => City.autocomplete(params[:q]), :status => 200
  end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def index
    @weather_infos = City.get_weather(params[:city_id], params[:city_name]) if params[:city_id] && params[:city_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/services/open_weather_map_sao.rb
module Services
  module OpenWeatherMapSao
    class << self
      require 'net/http'

      def get_request(url)
        url = URI.parse(url)
        req = Net::HTTP::Get.new(url.to_s)
        res = Net::HTTP.start(url.host, url.port) {|http|
          http.request(req)
        }
      end
      
      def get_weather_by_city_id(city_id)
        Rails.logger.info("calling weather api for city id #{city_id}")
        res = get_request("http://api.openweathermap.org/data/2.5/forecast?APPID=#{WeatherAppConfig.OPEN_WEATHER_MAP_API_KEY}&id=#{city_id}&units=metric")
        response = JSON.parse(res.body) rescue {"cod" => "500", :errors => ["Unable to parse openweathermap response"]}
        build_custom_weather_response(response)
      end

      def get_weather_by_city_name(city_name)
        res = get_request("http://api.openweathermap.org/data/2.5/forecast?APPID=#{WeatherAppConfig.OPEN_WEATHER_MAP_API_KEY}&q=#{city_name}&units=metric")
        response = JSON.parse(res.body) rescue {"cod" => "500", :errors => ["Unable to parse openweathermap response"]}
        build_custom_weather_response(response)
      end

      # If weather api response changes our clients will not break.
      def build_custom_weather_response(open_weather_response)
        response = {:status => open_weather_response["cod"], :errors => [], :weather_infos => []}
        if open_weather_response["cod"] == "200"
          response[:city_name] = "#{open_weather_response["city"]["name"]}, #{open_weather_response["city"]["country"]}"
          open_weather_response["list"].each do |info|
            # For cached results if some of them are before current time.
            if info["dt"] > Time.now.to_i
              weather_info  = {}
              weather_info[:datetime] = "#{info["dt_txt"]} UTC"
              main = info["main"]
              next unless main.present?
              weather_info[:temp] = {
                :curr => main["temp"],
                :min => main["temp_min"],
                :max => main["temp_max"],
                :metric => "°C"
              }
              weather_info[:humidity] = main["humidity"]
              weather_info[:more_info] = {
                :description => (info["weather"].first["description"] rescue ""),
                :weather_icon => (info["weather"].first["icon"] rescue ""),
                :wind_speed => ("#{info["wind"]["speed"]} m/s" rescue "")
              }
              response[:weather_infos] << weather_info
            end
          end
        elsif open_weather_response["cod"] == "404"
          response[:errors] << "We could not find for city you were looking for. Please try some other city."
        else
          Rails.logger.error("Something went wrong calling openweathermap ERROR: #{open_weather_response["errors"].join(",")}")
          response[:errors].add("We are sorry something went wrong. Please try again later")
        end
        response
      end

    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/index.html.erb
<% content_for :head do %>
    <title>Check Weather in your city</title>
<%end%>

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<div class="wrapper" style="padding:20px">
    <div class="row">
        <div class="col-sm-12">
            <%= form_tag weather_index_path, :method => 'get' do %>
              <p>
                <label for="city_id">City Name:</label>
                <%= text_field_tag :city_id, params[:city_id], placeholder: "Search Your City" , autocomplete: "off"%>
                <%= hidden_field_tag :city_name, params[:city_name], placeholder: "Search Your City" , autocomplete: "off"%>
                <%= submit_tag "Search", :name => nil, class: 'btn btn-primary' %>
              </p>
            <% end %>


            <%if @weather_infos.present?%>
                <%if @weather_infos[:errors].count > 0%>
                    <span class="text-danger"><%=@weather_infos[:errors].join(", ")%></span>
                <%else%>
                    <h4>Weather Forecast for <%=@weather_infos[:city_name]%></h4>
                    <table class="table table-hover table-striped">
                        <thead>
                            <th>Date-Time</th>
                            <th>Temprature</th>
                            <th>Humidity</th>
                            <th>Wind Speed</th>
                            <th>More Info</th>
                        </thead>
                        <tbody>
                            <%@weather_infos[:weather_infos].each do |weather_info|%>
                                <tr>
                                    <td><%=weather_info[:datetime]%></td>
                                    <%metric = weather_info[:temp][:metric]%>
                                    <td><%=weather_info[:temp][:curr].round(1)%><%=metric%></td>
                                    <td><%=weather_info[:humidity]%>%</td>
                                    <td><%=weather_info[:more_info][:wind_speed]%></td>
                                    <td><img src="http://openweathermap.org/img/w/<%=weather_info[:more_info][:weather_icon]%>.png"/><%=weather_info[:more_info][:description]%></td>
                                </tr>
                            <%end%>
                        </tbody>
                    </table>
                <%end%>
            <%end%>

            <script type="text/javascript">
                $(function(){
                    $("#city_id").tokenInput("<%=cities_autocomplete_path%>", 
                        {
                            'tokenLimit' : 1, 
                            placeholder: 'Start typing your city..',
                            'hintText' : 'Start typing your city..',
                            'noResultsText':'No Cities matching your search',
                            theme: "facebook", 
                            preventDuplicates: true,
                            onResult: function (item) {
                                if($.isEmptyObject(item)){
                                    return [{id:'0',name: $("tester").text()}]
                                }else{
                                    return item
                                }
                            },
                            onAdd: function (item) {
                                $("#city_name").val(item.name);
                            }
                        });
                });
            </script>
        </div>
    </div>
</div>